### ISSUE TITLE
transactionuser updates do not update transactions updated field, and as such an update scan will miss all changes 

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-elasticsearch#22]
### Scenario:
trying to run pacifica-elasticsearch with a --time-ago "60 days".  The newly released transactions do not appear in the elastic search index.
database for transaction user:
```
 transaction_id |       created       |       updated       | deleted | user_id |           relationship_id            |                 uuid
----------------+---------------------+---------------------+---------+---------+--------------------------------------+--------------------------------------
1624717 | 2019-10-05 03:57:22 | 2019-10-05 03:57:22 |         |   47946 | be0cd1a7-2ab1-463d-9a3e-94b513ddd558 | a36567da-bcd7-44dc-b7ef-31548efb0a7a
```
but yet the transaction does not show an update:
```
   id    |       created       |       updated       | deleted | suspense_date | description
---------+---------------------+---------------------+---------+---------------+-------------
 1624717 | 2018-09-13 18:57:31 | 2018-10-06 05:23:29 |         |               |
```

and so the script passes over it.

### Expected Result:
transactions recently released should appear as released in the index

### Actual Result:
no changes get made.

**Comment by dmlb2000** [comment]
I think I'm going to track this through several pull requests to start addressing this issue. They'll get added automatically here when the references are made.

**Comment by dmlb2000** [comment]
The list of objects that need to be updated are the following.

 - [x] `groups`
   - `instrument_group` and `instruments`
 - [x] `institutions`
   - `transactions` through `users`
   - may call into `users` query method to get this?
 - [x] `instruments`
   - `key_value_pairs`
   - `transactions` through `transsip`
 - [x] `projects`
   - `users`, `institutions`, `instruments`, `groups`, `science_themes`, `relationships`
   - `transactions` through `transsip` and `transsap` merged
 - [x] `transactions`
   - `users`, `instruments`, `groups`, `projects`, `key_value_pairs`, `files`, `relationships`
 - [x] `users`
   - `transsip` and `transsap` merge released check
   - `transsip` and `transsap` merge of transaction ids

Each of these needs a method now `get_select_query()` that should select the latest `time_field` from all related Pacifica Data Model objects, filter and page over the resulting objects.
